apiVersion: v1
kind: Service
metadata:
  name: fileferry-redis
  namespace: kube-system
spec:
  selector:
    app: fileferry-redis
  ports:
    - name: entry
      port: 6379
      targetPort: entry
  type: ClusterIP
