repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        args: [".", "--fix"]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["."]


  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.15.0
  #   hooks:
  #     - id: mypy
  #       args:
  #         - "--config-file=./fileferry/pyproject.toml"
  #         - "--explicit-package-bases"
  #         - "--show-traceback"
  #         # - "./fileferry/src"

