repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        args: [".", "--fix"]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["."]

  - repo: https://github.com/pre-commit/mirrors-pyright
    rev: v1.1.400
    hooks:
      - id: pyright
        name: pyright type check
        additional_dependencies: []


