version: '3.7'

services:

  service:
    container_name: fileferry
    build: ./fileferry
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./fileferry:/app
    depends_on:
      - db
      - redis
    env_file:
      - ./environments/.env
    ports:
      - "8000:8000"

  db:
    container_name: db
    image: postgres
    env_file:
      - ./environments/db.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    
    ports:
      - "15432:5432"
  
  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    restart: always
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres_data:
  redis_data: