version: "3.7"

services:
  fileferry:
    command: sh -c "pytest -v --tb=short --disable-warnings --maxfail=3 --cov=src --cov-report=term-missing --cov-report=html"
    volumes:
      - ./fileferry:/app
      - ./tests:/app/tests
      - ./pytest.ini:/app/pytest.ini
    environment:
      - PYTHONPATH=/app/src
      - ENVIRONMENT=test
    depends_on:
      - fileferry-db
      - fileferry-redis
      - fileferry-minio
