apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileferry-minio
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileferry-minio
  template:
    metadata:
      labels:
        app: fileferry-minio
    spec:
      containers:
        - name: fileferry-minio
          image: quay.io/minio/minio:latest
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          envFrom:
            - configMapRef:
                name: fileferry-minio-env
          ports:
            - name: api
              containerPort: 9000
              protocol: TCP
            - name: console
              containerPort: 9001
              protocol: TCP
          volumeMounts:
            - name: minio-data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: api
            initialDelaySeconds: 10
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: api
            initialDelaySeconds: 5
            periodSeconds: 10

      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc
