apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minio
  volumeName: minio-pv
  resources:
    requests:
      storage: 1Gi
