apiVersion: v1
kind: Service
metadata:
  name: fileferry-minio
  namespace: kube-system
spec:
  selector:
    app: fileferry-minio
  ports:
    - name: api
      port: 9000
      targetPort: api
    - name: console
      port: 9001
      targetPort: console
  type: ClusterIP
