groups:
  - name: fileferyy-alerts
    rules:
      - alert: FileferryRestartedRecently
        expr: fileferry_uptime < 300
        labels:
          severity: warning
        annotations:
          summary: "Fileferry was restarted less than 5 minutes ago"
          description: "Instance {{ $labels.instance }} has restarted recently (uptime under 5 minutes)."


      - alert: FileferryHealthcheckSlow
        expr: rate(http_request_latency_seconds_sum{path="/system/healthcheck", method="GET"}[1m])
              /
              rate(http_request_latency_seconds_count{path="/system/healthcheck", method="GET"}[1m])
              > 1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Healthcheck latency too high"
          description: "Average /system/healthcheck latency > 1s on instance {{ $labels.instance }}."
