from typing import AsyncIterator

import pytest
from domain.models.dataclasses import FileMeta
from infrastructure.models.sqlalchemy.file import File

@pytest.fixture
def valid_filemeta() -> FileMeta: ...
@pytest.fixture
def invalid_content_type_filemeta() -> FileMeta: ...
@pytest.fixture
def failed_filemeta() -> FileMeta: ...
@pytest.fixture
def valid_file() -> File: ...
@pytest.fixture
def fake_stream() -> AsyncIterator[bytes]: ...
