apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileferry
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileferry
  template:
    metadata:
      labels:
        app: fileferry
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: fileferry
          image: fileferry:latest
          workingDir: /app
          imagePullPolicy: IfNotPresent
          args:
            - uvicorn
            - transport.rest.main:app
            - --host
            - 0.0.0.0
            - --port
            - "8000"
            # - --reload
          env:
            - name: PYTHONPATH
              value: "/app/src"
            - name: MAIN_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key:  FILEFERRY_PATH

          envFrom:
            - configMapRef:
                name: fileferry-env
          ports:
            - name: entry
              containerPort: 8000
              protocol: TCP
          resources: {}
