apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: fileferry
  name: fileferry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fileferry
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/fileferry-default: "true"
        io.kompose.service: fileferry
    spec:
      containers:
        - name: fileferry
          image: fileferry:local
          workingDir: /app
          imagePullPolicy: IfNotPresent
          args:
            - uvicorn
            - transport.rest.main:app
            - --host
            - 0.0.0.0
            - --port
            - "8000"
            - --reload
          env:
            - name: PYTHONPATH
              value: "/app/src"
          envFrom:
            - configMapRef:
                name: fileferry-env
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
