from typing import Protocol

from sqlalchemy.ext.asyncio import AsyncSession


class TransactionContextContract(Protocol):
    """Контекст управления транзакцией."""

    _session: AsyncSession

    async def begin(self) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def close(self) -> None: ...
    @property
    def session(self) -> AsyncSession: ...
