from typing import Any, Protocol


class TransactionContextContract(Protocol):
    """Контекст управления транзакцией."""

    _session: Any  # тип сессии не задан явно, здесь может быть что угодно.

    async def begin(self) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def close(self) -> None: ...
    @property
    def session(self) -> Any: ...
