apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileferry-postgres-pv
spec:
  storageClassName: postgres
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/fileferry/postgres"
