apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileferry-postgres-pvc
  namespace: kube-system
spec:
  storageClassName: postgres
  volumeName: fileferry-postgres-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
