namespace: kube-system
resources:
  - db
  - fileferry
  - minio
  - redis


generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: fileferry-env
    envs:
      - environments/fileferry.env
      - environments/minio.default.env
      - environments/postgres.env
      - environments/redis.env
  - name: fileferry-postgres-env
    envs:
      - environments/postgres.env
  - name: fileferry-minio-env
    envs:
      - environments/minio.env

